Changes to menu to determine version
stickz/rtorrent pull request #17
Opened 2024-07-10 22:34 UTC by ac1dburnz

Just a general idea of how to make Changes to menu to determine version which are updated every release

2024-07-10 23:26 UTC, stickz requested changes

2024-07-10 23:26 UTC, stickz commented on rtorrent/src/main.cc
> +  std::cout << "This is stickz modified version 0.9.8-v5.0 of Rakshasa's BitTorrent client version " VERSION "." << std::endl;
Change to this:
`std::cout << "rtorrent stickz BitTorrent client version " STICKZ_VERSION "." << std::endl;`

Change this to link to the GitHub issues report section.
https://github.com/stickz/rtorrent/blob/6598f49fd548acaf44aaf102c1564c104b4c2e02/rtorrent/src/main.cc#L689

Add on Line 4: `AC_DEFINE(STICKZ_VERSION, "0.9.8-v5.0", rtorrent stickz version)`
https://github.com/stickz/rtorrent/blob/6598f49fd548acaf44aaf102c1564c104b4c2e02/rtorrent/configure.ac#L3-L4

2024-07-10 23:28 UTC, stickz commented
We're not changing the version we announce to peers in the BitTorrent stream yet. We need to coordinate this carefully.

2024-07-11 02:38 UTC, ac1dburnz commented
lmk if there is anything else.

2024-07-11 02:38 UTC, stickz requested changes

2024-07-11 02:38 UTC, stickz commented on rtorrent/src/main.cc
> +
**This is enough:** https://github.com/stickz/rtorrent/issues

2024-07-11 05:14 UTC, merged